name: get_flutter_fire
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.31.0
  firebase_ui_auth: ^1.14.0
  firebase_auth: ^4.19.5
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  google_fonts: ^6.2.1

dev_dependencies: 
  flutter_lints: 3.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  uses-material-design: true

